### ISSUE TITLE
baseplugin: Adding -0.55 rep restriction to dock

### ISSUE THREAD

**Issue by dd84ai** [DiscoveryGC/FLHook#142]
During defensemodes 2
People can dock based on their reputation

At the moment it is not restricting from docking people with -0.55 reputation
While actually supposed to block and say things like "Your reputation stinks" and other things that can be found in playercntl

It needs to be fixed, and I am recommending regulating it purely through base plugin in the next function:
static bool IsDockingAllowed(PlayerBase *base, uint client)

reputation can be acquired in this func
float PlayerBase::GetAttitudeTowardsClient(uint client)

**Comment by dd84ai** [comment]
After consideration, I decided to be not touching it until this thing is merged at least
https://github.com/DiscoveryGC/FLHook/pull/130

**Comment by Aingar** [comment]
Fixed at some point leading up to 5.0 release
