### ISSUE TITLE
bug(base) CLD3 shows as CLD2 during construction

### ISSUE THREAD

**Issue by dd84ai** [DiscoveryGC/FLHook#161]
How it was produced (quote): I can remember when I was putting a Cloak Disruptor Type-3 device to made in Ulster and then it showed it was making a Type 2. Now thats its made, it s a type 3.

Severity: Minor. It is just a cosmetic bug.

![image](https://user-images.githubusercontent.com/20555918/119262028-f23deb00-bc03-11eb-9b98-ace500bc69dc.png)

**Comment by Aingar** [comment]
Fixed at some point leading to 5.0 release.
