### ISSUE TITLE
Latest Base Plugin problems

### ISSUE THREAD

**Issue by brac3r** [DiscoveryGC/FLHook#188]
**From my server discord:**
"commands work but base info screen is borked"
[Image 1](https://cdn.discordapp.com/attachments/1080014677599342644/1087966490415865927/Capture.JPG)
[Image 2](https://cdn.discordapp.com/attachments/1080014677599342644/1087966490642370590/Capture.JPG)

"name still broken"
"From what i can tell my base is bugged in more ways than one, if it was only bugged in appearance (buggy menu) i would probably just put up with it. However a number of items in my base, i now don't seem to have any way to retrieve. I went through 1 by 1 and just set each resource in the base to have no minimum, which should make everything purchasable, however at least half of the commodities along with a hyperspace scanner are un-retrievable."

**How to reproduce**
Compile latest base plugin and flhook etc.. in this repository, start a new server. 
Try to do base stuff described above.

**Comment by Aingar** [comment]
You're missing dsacesrv.dll in your plugin directory. It's not buildable from this repository, but you can find a copy in a fresh Discovery client install. Just fixed that exact issue on my own test server.

Let me know if #181 also resolves with this fix :)

**Comment by brac3r** [comment]
Implemented the fix, hopefully I will be able to confirm it worked in the next few days.

**Comment by brac3r** [comment]
Can confirm bases are now working, players are happy with that, thanks! :)

Unfortunately #181 is still not working, tested about a minute ago.
