### ISSUE TITLE
Get this repository moved to @DiscoveryGC org and sort out permissions

### ISSUE THREAD

**Issue by dsyalex** [DiscoveryGC/FLHook#62]
I'd like to be able to assign issues to @Kazinsal, @LazDisco, @ConradWeiser, etc. but can't mess with the permissions while the repository is under alley directly.
Should also ask for DiscoveryApi to be moved

**Comment by dsyalex** [comment]
and hopefully fix #44 assignment

**Comment by dsyalex** [comment]
plus all the other things that now have the assignee Laz label

**Comment by zibbizor** [comment]
Move done
